apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\APPS\kompose\bin\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: webserver
status:
  loadBalancer: {}
